<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5241c702-a715-44b8-a332-53ad00ead884}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	sequencer : FB_Sequencer;
END_VAR



]]></Declaration>
    <Implementation>
      <ST><![CDATA[
sequencer();

 ]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="241" Count="0" />
      <LineId Id="236" Count="0" />
      <LineId Id="235" Count="0" />
      <LineId Id="208" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>