<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5241c702-a715-44b8-a332-53ad00ead884}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Motor1 : Motor;
	Overload : BOOL;
	OverloadMethod : BOOL;
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Motor1(Overload := Overload);
Motor1.FaultSet(OverloadMethod);
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="302" Count="0" />
      <LineId Id="316" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>